Update README.md
In this I added ```import os
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"``` so that if someone is using m1 macOS then they do not have to worry about the errors that I previously got which include problems with torch vision and `ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant'`